[package]
name = "browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.21.0"
rustls-native-certs = "0.6.3"
flate2 = "1.0"
chunked_transfer = "1.4.1"
